
# Project information
site_name: 'scraip site'
site_url: https://pimntochz.github.io/scraip/
use_directory_urls: false

# Page tree
nav:
  - Home: index.md
  - Bus solutions:
    - Bus solutions: bus-solutions/bus-solutions.md

#Repository
repo_name: pimntochz/scraip1
repo_url: https://github.com/pimntochz/scraip1
edit_uri: ""


# Configuration
theme:
  name: material
  palette:
    primary:
    accent:
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes

  font:
    text: Arial
    code: Roboto Mono

extra_css:
  - styles/extra.css

# Plugins
plugins:
  - search

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - attr_list

  - toc:
      permalink: true
  - codehilite:
      linenums: true



